// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRP-8Mj6YIpc6B-Ib8tv8_yhkmR94n1sI',
    appId: '1:448994899479:web:838bf84625bf12a9d6ce52',
    messagingSenderId: '448994899479',
    projectId: 'floodstore-fbece',
    authDomain: 'floodstore-fbece.firebaseapp.com',
    storageBucket: 'floodstore-fbece.firebasestorage.app',
    measurementId: 'G-16HR3BM68S',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbIRmYWD5aa6DKrtE9mjQ1t6RDtABAsPw',
    appId: '1:448994899479:android:8117f7164e0a2104d6ce52',
    messagingSenderId: '448994899479',
    projectId: 'floodstore-fbece',
    storageBucket: 'floodstore-fbece.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD9x6JQA-zS838FZ1rN_k0KNRAt3tYnXI',
    appId: '1:448994899479:ios:0bfd117ffd1b3a9ad6ce52',
    messagingSenderId: '448994899479',
    projectId: 'floodstore-fbece',
    storageBucket: 'floodstore-fbece.firebasestorage.app',
    iosBundleId: 'com.example.floodStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD9x6JQA-zS838FZ1rN_k0KNRAt3tYnXI',
    appId: '1:448994899479:ios:0bfd117ffd1b3a9ad6ce52',
    messagingSenderId: '448994899479',
    projectId: 'floodstore-fbece',
    storageBucket: 'floodstore-fbece.firebasestorage.app',
    iosBundleId: 'com.example.floodStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRP-8Mj6YIpc6B-Ib8tv8_yhkmR94n1sI',
    appId: '1:448994899479:web:03cc819f45297b6cd6ce52',
    messagingSenderId: '448994899479',
    projectId: 'floodstore-fbece',
    authDomain: 'floodstore-fbece.firebaseapp.com',
    storageBucket: 'floodstore-fbece.firebasestorage.app',
    measurementId: 'G-HH40WCNMER',
  );
}
