import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
import 'features/auth/application/providers/auth_providers.dart';
import 'features/auth/application/providers/security_providers.dart';

// Generated by `flutterfire configure`. Run that command once this project
// is linked to a real Firebase project — see README.md — then uncomment
// the import and DefaultFirebaseOptions.currentPlatform argument below.
// import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    // options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const ProviderScope(child: FloodStoreApp()));
}

class FloodStoreApp extends ConsumerStatefulWidget {
  const FloodStoreApp({super.key});

  @override
  ConsumerState<FloodStoreApp> createState() => _FloodStoreAppState();
}

class _FloodStoreAppState extends ConsumerState<FloodStoreApp> {
  bool _sessionRecordedForCurrentUser = false;

  @override
  Widget build(BuildContext context) {
    final router = ref.watch(goRouterProvider);

    ref.listen(authStateChangesProvider, (previous, next) {
      final user = next.asData?.value;
      if (user != null && !_sessionRecordedForCurrentUser) {
        _sessionRecordedForCurrentUser = true;
        ref.read(securityRepositoryProvider).recordSession();
      } else if (user == null) {
        _sessionRecordedForCurrentUser = false;
      }
    });

    return MaterialApp.router(
      title: 'FloodStore',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.dark,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.dark,
      routerConfig: router,
    );
  }
}
