import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:floodstore/features/b2b/application/providers/b2b_providers.dart';
import 'package:floodstore/features/b2b/domain/entities/purchase_request.dart';
import 'package:floodstore/features/b2b/domain/entities/purchase_request_item.dart';
import 'package:floodstore/core/theme/app_colors.dart';
import 'package:floodstore/core/theme/app_spacing.dart';
import 'package:floodstore/core/theme/app_text_styles.dart';
import 'package:floodstore/core/widgets/glass_card.dart';
import 'package:floodstore/core/widgets/premium_button.dart';

class CreatePurchaseRequestScreen extends ConsumerStatefulWidget {
  final String projectId;
  final String? phaseId; // Optional, if creating for a specific phase

  const CreatePurchaseRequestScreen({
    required this.projectId,
    this.phaseId,
    super.key,
  });

  @override
  ConsumerState<CreatePurchaseRequestScreen> createState() =>
      _CreatePurchaseRequestScreenState();
}

class _CreatePurchaseRequestScreenState
    extends ConsumerState<CreatePurchaseRequestScreen> {
  final _formKey = GlobalKey<FormState>();
  final _descriptionController = TextEditingController();
  final List<PurchaseRequestItem> _items = [];
  String _status = 'draft';

  @override
  void dispose() {
    _descriptionController.dispose();
    super.dispose();
  }

  void _addItem() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) => _AddItemBottomSheet(
        onItemAdded: (item) {
          setState(() {
            _items.add(item);
          });
        },
      ),
    );
  }

  void _removeItem(int index) {
    setState(() {
      _items.removeAt(index);
    });
  }

  void _submitRequest() async {
    if (!_formKey.currentState!.validate()) return;

    final userId = ref.read(currentUserIdProvider)!;
    if (userId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please log in first')),
      );
      return;
    }

    final purchaseRequest = PurchaseRequest(
      id: '', // Will be generated by backend
      projectId: widget.projectId,
      phaseId: widget.phaseId ?? '',
      requesterId: userId,
      requestDate: DateTime.now(),
      status: _status,
      items: List.from(_items),
    );

    setState(() => _isSubmitting = true);

    try {
      final savedRequest = await ref
          .read(createPurchaseRequestProvider)
          .call(purchaseRequest);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Purchase request submitted successfully')),
        );
        // TODO: Navigate to request detail or back to project detail
        Navigator.of(context).pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to submit request: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  bool _isSubmitting = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: Text(
          'Yeni Satınalma Tələbi',
          style: AppTextStyles.headlineMedium,
        ),
        centerTitle: true,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      body: SafeArea(
        child: Form(
          key: _formKey,
          child: ListView(
            padding: const EdgeInsets.all(AppSpacing.md),
            children: [
              GlassCard(
                padding: const EdgeInsets.all(AppSpacing.md),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Təsvir',
                      style: AppTextStyles.textTheme.titleMedium
                          ?.copyWith(fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: AppSpacing.xs),
                    TextFormField(
                      controller: _descriptionController,
                      decoration: InputDecoration(
                        hintText: 'Satınalma tələbinizi detallı şəkildə təsvir edin',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                        ),
                        filled: true,
                        fillColor: AppColors.card.withValues(alpha: 0.1),
                      ),
                      maxLines: 4,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Zəhmət olmazsa, təsviri daxil edin';
                        }
                        return null;
                      },
                    ),
                  ],
                ),
              ),
              const SizedBox(height: AppSpacing.md),
              GlassCard(
                padding: const EdgeInsets.all(AppSpacing.md),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          'Məhsullar',
                          style: AppTextStyles.textTheme.titleMedium
                              ?.copyWith(fontWeight: FontWeight.bold),
                        ),
                        TextButton.icon(
                          onPressed: _addItem,
                          icon: const Icon(Icons.add),
                          label: const Text('Əlavə Et'),
                        ),
                      ],
                    ),
                    const SizedBox(height: AppSpacing.sm),
                    _items.isEmpty
                        ? const Padding(
                            padding: EdgeInsets.symmetric(vertical: 16),
                            child: Text(
                              'Heç məhsul əlavə edilməyib',
                              style: TextStyle(
                                color: AppColors.textTertiary,
                                fontStyle: FontStyle.italic,
                              ),
                              textAlign: TextAlign.center,
                            ),
                          )
                        : ListView.builder(
                            shrinkWrap: true,
                            physics: const NeverScrollableScrollPhysics(),
                            itemCount: _items.length,
                            itemBuilder: (context, index) {
                              final item = _items[index];
                              return _ItemTile(
                                item: item,
                                index: index,
                                onRemoved: _removeItem,
                              );
                            },
                          ),
                  ],
                ),
              ),
              const SizedBox(height: AppSpacing.lg),
              PremiumButton(
                label: _isSubmitting ? 'Göndərilir...' : 'Göndər',
                icon: _isSubmitting ? null : Icons.send,
                expand: true,
                onPressed: _isSubmitting ? null : _submitRequest,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _ItemTile extends StatelessWidget {
  final PurchaseRequestItem item;
  final int index;
  final ValueChanged<int> onRemoved;

  const _ItemTile({
    required this.item,
    required this.index,
    required this.onRemoved,
  });

  @override
  Widget build(BuildContext context) {
    return GlassCard(
      padding: const EdgeInsets.all(AppSpacing.sm),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  item.description,
                  style: AppTextStyles.textTheme.bodyLarge
                      ?.copyWith(fontWeight: FontWeight.w600),
                ),
                const SizedBox(height: 4),
                Text(
                  '${item.quantity} ${item.unit} × \$${item.unitPrice.toStringAsFixed(2)} = \$${item.totalPrice.toStringAsFixed(2)}',
                  style: TextStyle(
                    fontSize: 14,
                    color: AppColors.textSecondary,
                  ),
                ),
                if (item.vendorSuggestion.isNotEmpty) ...[
                  const SizedBox(height: 4),
                  Text(
                    'Təbbiotoxatçı tövsiyyəsi: ${item.vendorSuggestion}',
                    style: TextStyle(
                      fontSize: 12,
                      color: AppColors.textTertiary,
                      fontStyle: FontStyle.italic,
                    ),
                  ),
                ],
              ],
            ),
          ),
          IconButton(
            icon: const Icon(Icons.delete_outline, color: AppColors.error),
            onPressed: () => onRemoved(index),
            tooltip: 'Sil',
          ),
        ],
      ),
    );
  }
}

class _AddItemBottomSheet extends ConsumerStatefulWidget {
  final ValueChanged<PurchaseRequestItem> onItemAdded;

  const _AddItemBottomSheet({required this.onItemAdded});

  @override
  ConsumerState<_AddItemBottomSheet> createState() =>
      _AddItemBottomSheetState();
}

class _AddItemBottomSheetState extends ConsumerState<_AddItemBottomSheet> {
  final _formKey = GlobalKey<FormState>();
  final _descriptionController = TextEditingController();
  final _quantityController = TextEditingController(text: '1');
  final _unitPriceController = TextEditingController();
  final _unitController = TextEditingController(text: 'pcs');
  final _vendorSuggestionController = TextEditingController();

  @override
  void dispose() {
    _descriptionController.dispose();
    _quantityController.dispose();
    _unitPriceController.dispose();
    _unitController.dispose();
    _vendorSuggestionController.dispose();
    super.dispose();
  }

  void _saveItem() {
    if (!_formKey.currentState!.validate()) return;

    final item = PurchaseRequestItem(
      id: DateTime.now().millisecondsSinceEpoch.toString(), // Temporary ID
      description: _descriptionController.text.trim(),
      quantity: int.parse(_quantityController.text),
      unitPrice: double.parse(_unitPriceController.text),
      unit: _unitController.text.trim(),
      vendorSuggestion: _vendorSuggestionController.text.trim(),
    );

    widget.onItemAdded(item);
    Navigator.of(context).pop();
  }

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
      initialChildSize: 0.9,
      minChildSize: 0.5,
      maxChildSize: 0.95,
      builder: (context, scrollController) => Container(
        decoration: const BoxDecoration(
          color: AppColors.background,
          borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
        ),
        child: ListView(
          controller: scrollController,
          padding: const EdgeInsets.all(AppSpacing.lg),
          children: [
            Text(
              'Yeni Mall Əlavə Et',
              style: AppTextStyles.textTheme.titleLarge
                  ?.copyWith(fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: AppSpacing.md),
            Form(
              key: _formKey,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  TextFormField(
                    controller: _descriptionController,
                    decoration: InputDecoration(
                      labelText: 'Mallar Tavsifi',
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Zəhmət olmazsa, tavsizi daxil edin';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: AppSpacing.sm),
                  Row(
                    children: [
                      Expanded(
                        child: TextFormField(
                          controller: _quantityController,
                          decoration: InputDecoration(
                            labelText: 'Miqdar',
                            border: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                          keyboardType: TextInputType.number,
                          validator: (value) {
                            if (value == null || value.isEmpty) {
                              return 'Zəhmət olmazsa, miqrağı daxil edin';
                            }
                            if (int.tryParse(value) == null ||
                                int.parse(value) <= 0) {
                              return 'Miqdar müsbət ədəd olmalıdır';
                            }
                            return null;
                          },
                        ),
                      ),
                      const SizedBox(width: AppSpacing.sm),
                      Expanded(
                        child: TextFormField(
                          controller: _unitPriceController,
                          decoration: InputDecoration(
                            labelText: 'Vahid qiymeti',
                            border: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(8),
                            ),
                          ),
                          keyboardType:
                              TextInputType.numberWithOptions(decimal: true),
                          validator: (value) {
                            if (value == null || value.isEmpty) {
                              return 'Zəhmət olmazsa, vahid qiymetini daxil edin';
                            }
                            if (double.tryParse(value) == null ||
                                double.parse(value) <= 0) {
                              return 'Vahid qiymeti müsbət ədəd olmalıdır';
                            }
                            return null;
                          },
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: AppSpacing.sm),
                  TextFormField(
                    controller: _unitController,
                    decoration: InputDecoration(
                      labelText: 'Vahid',
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                  ),
                  const SizedBox(height: AppSpacing.sm),
                  TextFormField(
                    controller: _vendorSuggestionController,
                    decoration: InputDecoration(
                      labelText: 'Təbbiotoxatçı Tövsiyyəsi (ixtiyari)',
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                  ),
                  const SizedBox(height: AppSpacing.lg),
                  SizedBox(
                    width: double.infinity,
                    child: PremiumButton(
                      label: 'Əlavə Et',
                      icon: Icons.add,
                      expand: true,
                      onPressed: _saveItem,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}