import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:floodstore/features/b2b/application/providers/b2b_providers.dart';
import 'package:floodstore/features/b2b/domain/entities/project.dart';
import 'package:floodstore/features/b2b/domain/entities/project_phase.dart';
import 'package:floodstore/core/theme/app_colors.dart';
import 'package:floodstore/core/theme/app_spacing.dart';
import 'package:floodstore/core/theme/app_text_styles.dart';
import 'package:floodstore/core/widgets/glass_card.dart';
import 'package:floodstore/core/widgets/premium_button.dart';

class CreateProjectScreen extends ConsumerStatefulWidget {
  final String organizationId;

  const CreateProjectScreen({required this.organizationId, super.key});

  @override
  ConsumerState<CreateProjectScreen> createState() => _CreateProjectScreenState();
}

class _CreateProjectScreenState extends ConsumerState<CreateProjectScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _descriptionController = TextEditingController();
  final List<ProjectPhase> _phases = [];
  String _status = 'planning'; // default status

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  void _addPhase() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) => _AddPhaseBottomSheet(
        onPhaseAdded: (phase) {
          setState(() {
            _phases.add(phase);
          });
        },
      ),
    );
  }

  void _removePhase(int index) {
    setState(() {
      _phases.removeAt(index);
    });
  }

  void _createProject() async {
    if (!_formKey.currentState!.validate()) return;

    final project = Project(
      id: '', // will be generated by backend
      organizationId: widget.organizationId,
      name: _nameController.text.trim(),
      description: _descriptionController.text.trim(),
      status: _status,
      phases: List.from(_phases),
      startDate: DateTime.now(),
      endDate: null, // can be set later
    );

    try {
      final createdProject = await ref
          .read(projectRepositoryProvider)
          .createProject(project);

      if (mounted) {
        // Navigate back to projects screen (maybe with success snackbar)
        if (context.mounted) {
          // Optionally show a snackbar
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Layihə yaradıldı')),
          );
          // Pop to previous screen (projects screen)
          Navigator.of(context).pop();
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Layihə yaradılarkən xəta: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: Text(
          'Yeni Layihə Yaradın',
          style: AppTextStyles.headlineMedium,
        ),
        centerTitle: true,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      body: SafeArea(
        child: Form(
          key: _formKey,
          child: ListView(
            padding: const EdgeInsets.all(AppSpacing.md),
            children: [
              GlassCard(
                padding: const EdgeInsets.all(AppSpacing.md),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Layihə Adı',
                      style: AppTextStyles.textTheme.titleMedium
                          ?.copyWith(fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: AppSpacing.xs),
                    TextFormField(
                      controller: _nameController,
                      decoration: InputDecoration(
                        hintText: 'Layihə adını daxil edin',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                        ),
                        filled: true,
                        fillColor: AppColors.card.withValues(alpha: 0.1),
                      ),
                      maxLines: 1,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Zəhmət olmazsa, layihə adını daxil edin';
                        }
                        return null;
                      },
                    ),
                  ],
                ),
              ),
              const SizedBox(height: AppSpacing.md),
              GlassCard(
                padding: const EdgeInsets.all(AppSpacing.md),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Təsvir',
                      style: AppTextStyles.textTheme.titleMedium
                          ?.copyWith(fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: AppSpacing.xs),
                    TextFormField(
                      controller: _descriptionController,
                      decoration: InputDecoration(
                        hintText: 'Layihə detallı təsvirini daxil edin',
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.circular(8),
                        ),
                        filled: true,
                        fillColor: AppColors.card.withValues(alpha: 0.1),
                      ),
                      maxLines: 4,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Zəhmət olmazta, təsviri daxil edin';
                        }
                        return null;
                      },
                    ),
                  ],
                ),
              ),
              const SizedBox(height: AppSpacing.md),
              GlassCard(
                padding: const EdgeInsets.all(AppSpacing.md),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          'Fazalar',
                          style: AppTextStyles.textTheme.titleMedium
                              ?.copyWith(fontWeight: FontWeight.bold),
                        ),
                        TextButton.icon(
                          onPressed: _addPhase,
                          icon: const Icon(Icons.add),
                          label: const Text('Faza Əlavə Et'),
                        ),
                      ],
                    ),
                    const SizedBox(height: AppSpacing.sm),
                    _phases.isEmpty
                        ? const Padding(
                            padding: EdgeInsets.symmetric(vertical: 16),
                            child: Text(
                              'Heç faza əlavə edilməyib',
                              style: TextStyle(
                                color: AppColors.textTertiary,
                                fontStyle: FontStyle.italic,
                              ),
                              textAlign: TextAlign.center,
                            ),
                          )
                        : ListView.builder(
                            shrinkWrap: true,
                            physics: const NeverScrollableScrollPhysics(),
                            itemCount: _phases.length,
                            itemBuilder: (context, index) {
                              final phase = _phases[index];
                              return _PhaseTile(
                                phase: phase,
                                index: index,
                                onRemoved: _removePhase,
                              );
                            },
                          ),
                  ],
                ),
              ),
              const SizedBox(height: AppSpacing.lg),
              PremiumButton(
                label: _phases.isEmpty ? 'Yarat' : 'Yarat',
                icon: Icons.add,
                expand: true,
                onPressed: _phases.isEmpty ? null : _createProject,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _PhaseTile extends StatelessWidget {
  final ProjectPhase phase;
  final int index;
  final ValueChanged<int> onRemoved;

  const _PhaseTile({
    required this.phase,
    required this.index,
    required this.onRemoved,
  });

  @override
  Widget build(BuildContext context) {
    return GlassCard(
      padding: const EdgeInsets.all(AppSpacing.sm),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  phase.name,
                  style: AppTextStyles.textTheme.bodyLarge
                      ?.copyWith(fontWeight: FontWeight.w600),
                ),
                const SizedBox(height: 4),
                Text(
                  '${phase.description} - \$${phase.budget.toStringAsFixed(2)}',
                  style: TextStyle(
                    fontSize: 14,
                    color: AppColors.textSecondary,
                  ),
                ),
              ],
            ),
          ),
          IconButton(
            icon: const Icon(Icons.delete_outline, color: AppColors.error),
            onPressed: () => onRemoved(index),
            tooltip: 'Sil',
          ),
        ],
      ),
    );
  }
}

class _AddPhaseBottomSheet extends ConsumerStatefulWidget {
  final ValueChanged<ProjectPhase> onPhaseAdded;

  const _AddPhaseBottomSheet({required this.onPhaseAdded});

  @override
  ConsumerState<_AddPhaseBottomSheet> createState() => _AddPhaseBottomSheetState();
}

class _AddPhaseBottomSheetState extends ConsumerState<_AddPhaseBottomSheet> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _budgetController = TextEditingController();

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    _budgetController.dispose();
    super.dispose();
  }

  void _savePhase() {
    if (!_formKey.currentState!.validate()) return;

    final phase = ProjectPhase(
      id: DateTime.now().millisecondsSinceEpoch.toString(), // temporary ID
      projectId: '', // will be set when project is created
      name: _nameController.text.trim(),
      description: _descriptionController.text.trim(),
      startDate: DateTime.now(),
      endDate: null,
      budget: double.tryParse(_budgetController.text) ?? 0.0,
      status: 'planned',
    );

    widget.onPhaseAdded(phase);
    Navigator.of(context).pop();
  }

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
      initialChildSize: 0.9,
      minChildSize: 0.5,
      maxChildSize: 0.95,
      builder: (context, scrollController) => Container(
        decoration: const BoxDecoration(
          color: AppColors.background,
          borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
        ),
        child: ListView(
          controller: scrollController,
          padding: const EdgeInsets.all(AppSpacing.lg),
          children: [
            Text(
              'Yeni Faza Əlavə Et',
              style: AppTextStyles.textTheme.titleLarge
                  ?.copyWith(fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: AppSpacing.md),
            Form(
              key: _formKey,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  TextFormField(
                    controller: _nameController,
                    decoration: InputDecoration(
                      labelText: 'Faza Adı',
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Zəhmət olmazsa, faza adını daxil edin';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: AppSpacing.sm),
                  TextFormField(
                    controller: _descriptionController,
                    decoration: InputDecoration(
                      labelText: 'Faza Tavsifi',
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                    maxLines: 3,
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Zəhmət olmazsa, tavsizi daxil edin';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: AppSpacing.sm),
                  TextFormField(
                    controller: _budgetController,
                    decoration: InputDecoration(
                      labelText: 'Büdcə (USD)',
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                    keyboardType:
                        TextInputType.numberWithOptions(decimal: true),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Zəhmət olmazsa, büdceni daxil edin';
                      }
                      if (double.tryParse(value) == null ||
                          double.parse(value) < 0) {
                        return 'Büdcə müsbət ədəd olmalıdır';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: AppSpacing.lg),
                  SizedBox(
                    width: double.infinity,
                    child: PremiumButton(
                      label: 'Əlavə Et',
                      icon: Icons.add,
                      expand: true,
                      onPressed: _savePhase,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}